version: '3'
services: 
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  
  imagedb:
    image: fpommerening/msrmq:picflow-database
    ports:
      - 5432:5432
    hostname: imagedb
  
  documentdb:
    image: mongo:3.2
    ports:
      - 27017:27017
    
  externaldb:
    image: mongo:3.2
    
  extapp:
    image: fpommerening/msrmq:picflow-extapp
    depends_on:
      - externaldb
    ports:
      - 8000:8000
    environment:
      - ConnectionStringEntryDB=mongodb://externaldb
    
  uploader:
    image: fpommerening/msrmq:picflow-uploader
    depends_on:
      - rabbitmq
      - documentdb
      - extapp
    hostname: uploader
    environment:
      - ConnectionStringRabbitMQ=host=rabbitmq
      - ConnectionStringDocumentDB=mongodb://documentdb
      - ExternalAppUrl=http://extapp:8000/api/postimage
    
  processor:
    image: fpommerening/msrmq:picflow-processor
    depends_on:
      - rabbitmq
      - documentdb
    environment:
      - ConnectionStringRabbitMQ=host=rabbitmq
      - ConnectionStringDocumentDB=mongodb://documentdb
    
  authorization:
    image: fpommerening/msrmq:picflow-authorization
    depends_on:
      - rabbitmq
      - imagedb
    environment:
      - ConnectionStringRabbitMQ=host=rabbitmq
      - ConnectionStringImageDB=host=imagedb;database=msrmq;password=leipzig;username=msrmq
    
  persistor:
    image: fpommerening/msrmq:picflow-persistor
    depends_on:
      - rabbitmq
      - imagedb
      - documentdb
    environment:
      - ConnectionStringRabbitMQ=host=rabbitmq
      - ConnectionStringImageDB=host=imagedb;database=msrmq;password=leipzig;username=msrmq
      - ConnectionStringDocumentDB=mongodb://documentdb

  webapp:
    image: fpommerening/msrmq:picflow-webapp
    depends_on:
      - rabbitmq
      - imagedb
      - documentdb
      - persistor
      - authorization
      - uploader
      - processor
    ports:
      - 5000:5000
    environment:
      - ConnectionStringRabbitMQ=host=rabbitmq
      - ConnectionStringImageDB=host=imagedb;database=msrmq;password=leipzig;username=msrmq
      - ConnectionStringDocumentDB=mongodb://documentdb
